<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityUserRoleStateRepository extends EntityRepository
{
    /**
     *
     * @return CommunityUserRoleState|null
     */
    public function findPendingState()
    {
        return $this->createQueryBuilder('state')
            ->where('state.id=3000')
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     *
     * @return CommunityUserRoleState|null
     */
    public function findRejectState()
    {
        return $this->createQueryBuilder('state')
            ->where('state.id=2000')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
