<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CommunityRole;
use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRoleRepository extends EntityRepository
{

    /**
     *
     * @return CommunityRole|null
     */
    public function findAdminRole()
    {
        return $this->createQueryBuilder('role')
            ->where('role.id=100')
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     *
     * @return CommunityRole|null
     */
    public function findMemberRole()
    {
        return $this->createQueryBuilder('role')
            ->where('role.id=200')
            ->getQuery()
            ->getOneOrNullResult();
    }

}
