<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CommunityLink;
use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityLinkRepository extends EntityRepository
{
    /**
     *
     * @param array $communityIdList The community id list
     * @return CommunityLink|null
     */
    public function findCommunityLinksByCommunityIdList($communityIdList)
    {
        return $this->createQueryBuilder('communityLinks')
            ->join('communityLinks.community', 'community')
            ->where('community.id IN (:communityIdList)')
            ->setParameter('communityIdList', $communityIdList)
            ->getQuery()
            ->getResult();
    }

    
    /**
     *
     * @param array $communityId The community id
     * @return CommunityLink|null
     */
    public function findCommunitySocialNetworksByCommunityId($communityId)
    {
        return $this->createQueryBuilder('communityLinks')
            ->join('communityLinks.community', 'community')
            ->join('communityLinks.socialNetwork', 'socialNetwork')
            ->where('community.id =:communityId')
            ->setParameter('communityId', $communityId)
            ->getQuery()
            ->getResult();
    }

}
