<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CommunityUser;
use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityUserRepository extends EntityRepository
{

    /**
     *
     * @return CommunityUser|null
     */
    public function findAllExceptAdmin()
    {
        return $this->createQueryBuilder('communityUser')
            ->where('communityUser.user != :adminId')
            ->setParameter('adminId', 18)
            ->getQuery()
            ->getResult();
    }

}
