<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    /**
     *
     * @param string $username The username
     * @return UserInterface|null
     */
    public function findEventsByCommunityId($communityId)
    {
        return $this->createQueryBuilder('event')
            ->join('event.communityUser', 'communityUser')
            ->join('communityUser.community', 'community')
            ->where('community.id = :communityId')
            ->orderBy('event.startDate', 'DESC')
            ->setParameter('communityId', intval($communityId))
            ->getQuery()
            ->getResult();
    }


    /**
     *
     * @param array $communityIdList The community id list
     * @return UserInterface|null
     */
    public function findEventsByCommunityIdList($communityIdList)
    {
        return $this->createQueryBuilder('event')
            ->join('event.communityUser', 'communityUser')
            ->innerJoin('communityUser.community', 'community')
            ->where('community.id IN (:communityIdList)')
            ->setParameter('communityIdList', $communityIdList)
            ->getQuery()
            ->getResult();
    }


    /**
     *
     * @param \DateTime $datetime The date
     * @return UserInterface|null
     */
    public function findEventsByDate($firstDate , $lastDate)
    {
        return $this->createQueryBuilder('event')
            ->where('event.startDate BETWEEN :targetDate AND :targetNextDate')
            ->setParameter('targetDate', $firstDate)
            ->setParameter('targetNextDate', $lastDate)
            ->getQuery()
            ->getResult();
    }

}
