<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityRepository extends EntityRepository
{


    /**
     *
     * Üniversitenin toplam topluluk sayısını döner. Topluluğun onaylanıp onaylanmadığına bakılmaz
     *
     * @param string $universityId The university id
     * @return int|null
     */
    public function findUniversityCommunityCount($universityId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT COUNT(community.id) as communityCount
                    FROM AppBundle:University university
                    JOIN AppBundle:Community community WITH community.university=university.id
                    WHERE university.id = :universityId and community.isApproved=true
                '
        )->setParameters(array(
            'universityId' => $universityId
        ));

        return isset($query->getOneOrNullResult()['communityCount']) ? $query->getOneOrNullResult()['communityCount'] : 0;
    }

}
