# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\AdminUser:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        admin_db_provider:
            entity:
                class: AppBundle:AdminUser
                # property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~
            provider: admin_db_provider

            form_login:
                login_path: admin_homepage
                check_path: login
                failure_path: login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            logout:
                path:   /logout
                target: /