# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    acme.security.authentication_failure_event_listener:
            class: AppBundle\Listener\AuthenticationListener
            tags:
                - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
            arguments:
                - @doctrine.orm.entity_manager

    # authentication success event listener
    acme.security.interactive_login_listener:
        class: AppBundle\Listener\AuthenticationListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }
        arguments:
            - @doctrine.orm.entity_manager


    graylogger:
        parent: monolog.logger.graylog
        tags:
            - { name: monolog.logger, channel: graylog }